fix: disabling inlining when building glibc headers
When clang builds with optimization flags it causes glibc
to define __USE_EXTERN_INLINES macro
https://github.com/gcc-mirror/gcc/blob/2467998373b9b6ddd3dae1b8ea72c1ee3054c699/fixincludes/tests/base/features.h#L12-L16
This causes compilation errors like,

In file included from ../src/unix/legacy.cc:12:
/usr/include/x86_64-linux-gnu/sys/stat.h:449:8: error: exception specification in declaration does not match previous declaration
__NTH (stat (const char *__path, struct stat *__statbuf))
       ^
/usr/include/x86_64-linux-gnu/sys/stat.h:213:28: note: previous declaration is here
extern int __REDIRECT_NTH (stat, (const char *__restrict __file,